#!/usr/bin/env bash
#
# install-claude-hook.sh — wire this vault's session logger into Claude Code.
# Run once per machine. Safe to re-run; it is idempotent.
#
#   bash "<vault>/_bin/install-claude-hook.sh"            install
#   bash "<vault>/_bin/install-claude-hook.sh" --check     show what is registered
#   bash "<vault>/_bin/install-claude-hook.sh" --nested    use the nested hook schema
#   bash "<vault>/_bin/install-claude-hook.sh" --uninstall remove it
#
# Why a wrapper script: the vault path may contain spaces ("Obsidian Vault"), which
# would break a hook command string. We generate ~/.claude/hooks/obsidian-session-log
# with the path safely quoted inside, and register that space-free path instead.

set -uo pipefail

VAULT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
HOOK_DIR="$CLAUDE_DIR/hooks"
WRAPPER="$HOOK_DIR/obsidian-session-log"
SETTINGS="$CLAUDE_DIR/settings.json"
MODE="install"
SCHEMA="flat"

for arg in "$@"; do
  case "$arg" in
    --check)     MODE="check" ;;
    --uninstall) MODE="uninstall" ;;
    --nested)    SCHEMA="nested" ;;
    --help|-h)   sed -n '2,20p' "${BASH_SOURCE[0]}"; exit 0 ;;
  esac
done

say()  { printf '%s\n' "$*"; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- interpreter check
PY=""
for cand in python3 python; do
  if command -v "$cand" >/dev/null 2>&1; then
    if "$cand" -c 'import sys; sys.exit(0 if sys.version_info>=(3,7) else 1)' 2>/dev/null; then
      PY="$(command -v "$cand")"; break
    fi
  fi
done
[ -n "$PY" ] || die "need python3 >= 3.7 on PATH (checked python3, python)"

[ -f "$VAULT/_bin/claude-session-log.py" ] || die "logger not found at $VAULT/_bin/claude-session-log.py"

# ------------------------------------------------------------------------- check
if [ "$MODE" = "check" ]; then
  say "vault:       $VAULT"
  say "python:      $PY"
  say "wrapper:     $WRAPPER $([ -x "$WRAPPER" ] && echo '(present)' || echo '(MISSING)')"
  say "settings:    $SETTINGS $([ -f "$SETTINGS" ] && echo '(present)' || echo '(missing)')"
  if [ -f "$SETTINGS" ]; then
    say ""
    say "registered SessionEnd hooks:"
    "$PY" - "$SETTINGS" <<'PYC'
import json,sys
try: d=json.load(open(sys.argv[1]))
except Exception as e: print("  (settings.json is not valid JSON: %s)"%e); raise SystemExit
ents=(d.get("hooks") or {}).get("SessionEnd") or []
if not ents: print("  (none)")
for e in ents:
    if isinstance(e,dict) and "hooks" in e:
        for h in e["hooks"]: print("  nested:", h.get("command"))
    elif isinstance(e,dict): print("  flat:  ", e.get("command"))
PYC
  fi
  say ""
  say "recent session notes:"
  ls -1t "$VAULT/Log/Sessions" 2>/dev/null | head -5 | sed 's/^/  /' || say "  (none yet)"
  exit 0
fi

mkdir -p "$HOOK_DIR" || die "cannot create $HOOK_DIR"

# ------------------------------------------------------------------------ backup
if [ -f "$SETTINGS" ]; then
  cp "$SETTINGS" "$SETTINGS.bak.$(date +%Y%m%d%H%M%S)" 2>/dev/null && \
    say "backed up existing settings.json"
fi

# ----------------------------------------------------------------------- wrapper
if [ "$MODE" = "install" ]; then
  cat > "$WRAPPER" <<WRAP
#!/bin/sh
# Generated by install-claude-hook.sh — do not edit; re-run the installer instead.
VAULT='$(printf '%s' "$VAULT" | sed "s/'/'\\\\''/g")'
exec '$PY' "\$VAULT/_bin/claude-session-log.py" "\$@"
WRAP
  chmod +x "$WRAPPER" || die "cannot chmod $WRAPPER"
  say "wrote wrapper: $WRAPPER"
  mkdir -p "$VAULT/Log/Sessions"
fi

# ------------------------------------------------------- merge into settings.json
"$PY" - "$SETTINGS" "$WRAPPER" "$MODE" "$SCHEMA" <<'PYM'
import json, os, sys

settings_path, wrapper, mode, schema = sys.argv[1:5]

data = {}
if os.path.exists(settings_path):
    try:
        with open(settings_path) as fh:
            txt = fh.read().strip()
        data = json.loads(txt) if txt else {}
    except Exception as e:
        print("  settings.json was not valid JSON (%s)." % e)
        print("  Refusing to overwrite it. Fix or move it, then re-run.")
        sys.exit(1)
if not isinstance(data, dict):
    print("  settings.json is not a JSON object. Refusing to touch it."); sys.exit(1)

hooks = data.setdefault("hooks", {})
if not isinstance(hooks, dict):
    print("  'hooks' key is not an object. Refusing to touch it."); sys.exit(1)
entries = hooks.get("SessionEnd")
if not isinstance(entries, list):
    entries = []

def commands_in(entry):
    if not isinstance(entry, dict):
        return []
    if isinstance(entry.get("hooks"), list):
        return [h.get("command") for h in entry["hooks"] if isinstance(h, dict)]
    return [entry.get("command")]

# Drop any prior registration of ours, wherever it sits.
cleaned = []
removed = 0
for e in entries:
    cmds = commands_in(e)
    if wrapper in cmds:
        if isinstance(e, dict) and isinstance(e.get("hooks"), list):
            kept = [h for h in e["hooks"] if isinstance(h, dict) and h.get("command") != wrapper]
            removed += len(e["hooks"]) - len(kept)
            if kept:
                e["hooks"] = kept
                cleaned.append(e)
            continue
        removed += 1
        continue
    cleaned.append(e)

if mode == "uninstall":
    if removed:
        print("  removed %d registration(s)" % removed)
    else:
        print("  nothing was registered")
else:
    hook_obj = {"type": "command", "command": wrapper, "timeout": 60, "async": True}
    cleaned.append(hook_obj if schema == "flat" else {"hooks": [hook_obj]})
    print("  registered SessionEnd hook (%s schema)" % schema)

if cleaned:
    hooks["SessionEnd"] = cleaned
else:
    hooks.pop("SessionEnd", None)
if not hooks:
    data.pop("hooks", None)

os.makedirs(os.path.dirname(settings_path), exist_ok=True)
tmp = settings_path + ".tmp"
with open(tmp, "w") as fh:
    json.dump(data, fh, indent=2)
    fh.write("\n")
os.replace(tmp, settings_path)
print("  wrote %s" % settings_path)
PYM
rc=$?
[ $rc -eq 0 ] || die "settings.json was not modified"

if [ "$MODE" = "uninstall" ]; then
  rm -f "$WRAPPER" 2>/dev/null && say "removed wrapper"
  say ""; say "Uninstalled. Existing session notes were left alone."
  exit 0
fi

# ------------------------------------------------------------------------ verify
say ""
say "Self-test:"
"$PY" "$VAULT/_bin/claude-session-log.py" --self-test | tail -3 | sed 's/^/  /'

MACHINE="$(hostname -s 2>/dev/null || echo unknown)"
say ""
say "Installed on '$MACHINE'."
say ""
say "  vault    $VAULT"
say "  notes    $VAULT/Log/Sessions/"
say "  wrapper  $WRAPPER"
say ""
say "Verify: start a Claude Code session anywhere, type one prompt, exit,"
say "then run:  bash \"\$VAULT/_bin/install-claude-hook.sh\" --check"
say ""
say "If no note appears, the hook schema may differ on your Claude Code version."
say "Re-run with --nested to switch schemas, then try again."
